name: shikimori_api
description: A pure dart, ultra-lite package to interact with the Shikimori API.
version: 0.0.1
repository: https://github.com/ikramhasan/shikimori-api-client-dart
homepage: https://github.com/ikramhasan/shikimori-api-client-dart
issue_tracker: https://github.com/ikramhasan/shikimori-api-client-dart/issues
topics:
  - shikimori
  - api
  - dart
  - anime
  - manga
screenshots:
  - description: The banner image
  - path: https://raw.githubusercontent.com/ikramhasan/shikimori-api-client-dart/main/docs/banner.png

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
